run:
  deadline: 5m
  allow-parallel-runners: true

issues:
  max-issues-per-linter: 10

linters:
  enable:
    - copyloopvar
    - cyclop
    - dupl
    - dupword
    - errname
    - errorlint
    - exhaustive
    - funlen
    - gci
    - godot
    - gofmt
    - gosimple
    - govet
    - intrange
    - misspell
    - nestif
    - nilerr
    - nlreturn
    - nolintlint
    - paralleltest
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
  presets:
    - bugs
    - unused
  disable:
    - musttag # Extremely slow, at least on CI machines
linters-settings:
  cyclop:
    max-complexity: 10
    skip-tests: true
  exhaustive:
    default-signifies-exhaustive: true
  funlen:
    lines: 60
    ignore-comments: true
  gci:
    sections:
      - standard
      - dot
      - alias
      - default
      - localmodule
    custom-order: true
  gosimple:
    # See https://golangci-lint.run/usage/linters#gosimple for a breakdown of what's checked by this linter
    checks:
      - "all"
      - "-S1002" # Comparison to bool explicitly can sometimes add clarity
      - "-S1016" # Uncommon language feature, encourages coupling when it may not be appropriate
  govet:
    enable-all: true
    disable:
      - fieldalignment
  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true
  prealloc:
    simple: false
    for-loops: true
  revive:
    enable-all-rules: true
    rules:
      - name: add-constant
        disabled: true
      - name: cognitive-complexity
        disabled: false
      - name: cyclomatic
        disabled: false
      - name: dot-imports
        arguments:
          [
            "allowedPackages":
              ["github.com/onsi/ginkgo/v2", "github.com/onsi/gomega"],
          ]
      - name: function-length
        disabled: true
      - name: line-length-limit
        disabled: false
        arguments: [100]
      - name: unhandled-error
        disabled: true

  unused:
    generated-is-used: true

  wsl:
    allow-cuddle-declarations: true
