run:
  deadline: 5m
  allow-parallel-runners: true

linters:
  enable:
    - gofmt
    - staticcheck
    - gosimple
    - unused
    - tparallel
    - paralleltest
    - prealloc
    - unparam # This was added while we used go1.18 which means it's always been disabled. It may eventually be re-enabled and we'll need to fix what it finds
  presets:
    - bugs
    - unused
  disable:
    - musttag # Extremely slow, at least on CI machines
linters-settings:
  cyclop:
    max-complexity: 10
    skip-tests: true
  exhaustive:
    default-signifies-exhaustive: true
  gosimple:
    # See https://golangci-lint.run/usage/linters#gosimple for a breakdown of what's checked by this linter
    checks:
      - "all"
      - "-S1002" # Comparison to bool explicitly can sometimes add clarity
      - "-S1016" # Uncommon language feature, encourages coupling when it may not be appropriate
  govet:
    shadow: true
  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true
  prealloc:
    simple: false
    for-loops: true
  unused:
    generated-is-used: true
