version: v2.6.2
name: golangci-lint-custom
destination: $TOOL_DEST
plugins:
  - module: "go.uber.org/nilaway"
    import: "go.uber.org/nilaway/cmd/gclplugin"
    version: latest # Or a fixed version for reproducible builds.
