name: Validate Pull Request
on:
  workflow_dispatch:
    # No configuration, but allows manual triggering

  pull_request:
    branches:
      - main

  merge_group:
    branches:
      - main
    types: [checks_requested]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required to access tags
          submodules: "true"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build devcontainer image and push
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/theunrepentantgeek/crddoc-devcontainer
          push: always

      - name: Run task ci in devcontainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/theunrepentantgeek/crddoc-devcontainer
          push: never
          runCmd: task ci
