name: Validate Pull Request
on:
  workflow_dispatch:
    # No configuration, but allows manual triggering

  pull_request:
    branches:
      - main

  merge_group:
    branches:
      - main
    types: [checks_requested]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required to access tags
          submodules: "true"

      - name: Pre-build devcontainer image and run task ci
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/theunrepentantgeek/crddoc-devcontainer
          push: always
          runCmd: task ci
